name: SonarQube Cloud Analysis

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sonarqube:
    name: SonarQube Cloud Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Generate Coverage Report
        run: |
          pip install -r requirements-dev.txt
          pytest tests/ --cov=app --cov-report=xml:coverage.xml --junitxml=test-results.xml

      - name: Run SonarQube Cloud Analysis
        uses: SonarSource/sonarqube-scan-action@v4.3.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        continue-on-error: true
